---
title: "New York Times Dataset from 2012 - Homework 1"
author: "Sophia"
date: "31/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=F, warning=F}
# load data and packages
library(dplyr)
library(ggplot2)
library(doBy)
library(tidyverse)
# viridis colour palette
library(viridis)

data1 <- read.csv(url("https://stat.columbia.edu/~rachel/datasets/nyt1.csv"))
head(data1)
```
Exercise 1

```{r}
# Gender is coded as 0 = female, 1 = male
data1$Gender <- ifelse(data1$Gender == 0, "female", "male")

# New variable age_group for age categories
data1$age_group <- case_when(
  data1$Age <= 18 ~ "<18",
  data1$Age == 18 | data1$Age <= 24 ~ "18-24",
  data1$Age == 25 | data1$Age <= 35 ~ "25-34",
  data1$Age == 35 | data1$Age <= 44 ~ "35-44",
  data1$Age == 45 | data1$Age <= 54 ~ "45-54",
  data1$Age == 55 | data1$Age<= 64 ~ "55-64",
  data1$Age >= 65 ~ "65+")
head(data1)

# check for missing values
sum(is.na(data1))

descriptives <- function(x){c(length(x), min(x),max(x), mean(x), median(x))}
group_stats <- summaryBy(Age~age_group, data =data1, FUN=descriptives)

# rename columns 
colnames(group_stats) <- c("Age_group", "Length", "Min_value", "Max_value","Mean","Median")

print(group_stats)

```
Exercise 2
```{r}
# plot distributions of no. impressions and click-through-rate for these 6 age groups
# click-through-rate (CTR) = no. clicks/no. impressions
data1$click_rate <- data1$Clicks/data1$Impressions

# Exclude cases where there are no impressions nor clicks and only use data from users that are signed in
data1_filt <- data1 %>%
  filter(Clicks > 0,
         Impressions > 0,
         Signed_In == 1)


```

```{r}
# plot CTR
ctr_plot <- ggplot(data1_filt, aes(x = click_rate, fill = age_group))+
  geom_histogram(binwidth =0.1,position = "dodge")+
  ggtitle("Distribution of Click-Through Rates") +
  xlab("Click-Through Rate") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))+
  scale_fill_viridis(discrete = TRUE)
print(ctr_plot)

# plot for impressions
im_plot <- ggplot(data1_filt, aes(x = Impressions, fill = age_group)) +
  geom_histogram(binwidth =1, position = "dodge", alpha = 0.8)+
  ggtitle("Distribution of Impressions") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))
print(im_plot)

# define new variable to segment or categorize users based on their click behaviour
# low vs. high CTR
ctr_med <- median(data1_filt$click_rate)
data1_filt$ctr_cat <- ifelse(data1_filt$click_rate <= ctr_med, "low", 
                             "high") 
  
# Explore the data and make visual and quantitative comparisons across user segments/demographics (<18-year-old males versus < 18-year-old females or logged-in versus not, for example).

u18_males <- data1_filt %>%
  filter(Gender == "male", Age < 18 )

u18_females <- data1_filt %>%
  filter(Gender == "female", Age < 18 )

u18 <- full_join(u18_females, u18_males)

# group sizes
n_u18_males <- nrow(u18_males)
n_u18_females <- nrow(u18_females)

# group descriptives
male_table <- u18_males %>%
  group_by(Age) %>%
  summarise(n_males = n(), mean_CTR = mean(click_rate), med_CTR = median(click_rate))

female_table <- u18_females %>%
  group_by(Age) %>%
  summarise(n_females = n(), mean_CTR = mean(click_rate), med_CTR = median(click_rate))

# mean CTRs
mean_ctr_mal <- mean(u18_males$click_rate)
mean_ctr_fem <- mean(u18_females$click_rate)

# can see a gamma distribution of CTR in both groups
ctr_plot <- ggplot(u18, aes(x = u18$click_rate, fill = Gender)) +
  geom_density(binwidth =1, alpha = 0.5, position = "dodge")+
  ggtitle("Distribution of CTR in Males & Females Under 18") + 
  xlab("Click-Through Rate") + 
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))
print(ctr_plot)


##TODO Compare two groups' CTRs
t_test <- t.test(click_rate~Gender, data = data1_filt)
tidy_ttest <- broom::tidy(t_test)
p_val <- tidy_ttest$p.value
print(p_val)
 
##TODO Describe & interpret any patterns you find

```


